### ISSUE TITLE
Cannot create database sometimes

### ISSUE THREAD

**Issue by Kaju-Bubanja** [oddjobz/pynndb#5]
Sometimes about 30% of the time I try to create a database I get following stacktrace.
Not sure exactly why this happens, the relevant surrounding code is:
```
if debug:
    try:
        shutil.rmtree("database")
    except Exception:
        pass
db = Database('database')
```

Maybe I should wait after the delete for a short time?

```
Traceback (most recent call last):
  File "home\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "home\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "my_file.py", line 326, in my_function
    db = Database('database')
  File "home\my_project\venv\lib\site-packages\pymamba\__init__.py", line 232, in __init__
    self._env = Environment(name, **conf)
lmdb.Error: database: Input/output error

Exception ignored in: <bound method Database.__del__ of <pymamba.Database object at 0x000001BCCE8A7908>>
Traceback (most recent call last):
  File "home\my_project\venv\lib\site-packages\pymamba\__init__.py", line 245, in __del__
    self.close()
  File "home\my_project\venv\lib\site-packages\pymamba\__init__.py", line 323, in close
    if self._env:
AttributeError: 'Database' object has no attribute '_env'

```

**Comment by oddjobz** [comment]
No, there will be something else amiss .. check out the unit tests, these do an "rm -rf" before each 'open' with no timing issues.

**Comment by Kaju-Bubanja** [comment]
Just to be sure pynndb does support concurrent access, right?

**Comment by oddjobz** [comment]
pynndb supports what lmdb supports (so yes :) ) .. but it also has the same requirements and limitations as lmdb, for example you should only open the environment once, if you are using threads you should inherit the connection from your main process rather than opening the environment again. If on the other hand you are using multi-process, then you 'should' open a clean environment.  i.e. calling Database('db') twice from within the same process or thread tree is bad, and trying to inherit Database('db') across a fork() or similar probably isn't a good idea either.

**Comment by Kaju-Bubanja** [comment]
Thank you for the advice, I didn't know the limitation in threads. Now it works better and I don't get any errors anymore :)
